# Generated by Django 5.2.3 on 2025-07-01 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="tax_checklist_attachments/")),
                (
                    "tag",
                    models.CharField(
                        help_text="Type or description of the document (e.g., W-2, 1099, Receipt)",
                        max_length=100,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_attachments",
                        to="profiles.taxchecklistitem",
                    ),
                ),
            ],
        ),
    ]
