# Generated by Django 5.2.4 on 2025-07-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_processingtask_task_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingtask",
            name="task_log",
        ),
    ]
