# Generated by Django 5.2.3 on 2025-07-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_checklistattachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxchecklistitem",
            name="attachments",
        ),
    ]
