# Generated by Django 5.2.4 on 2025-07-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_processingtask_task_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingtask",
            name="transactions",
            field=models.ManyToManyField(
                blank=True, related_name="processing_tasks", to="profiles.transaction"
            ),
        ),
    ]
