# Generated by Django 5.2.1 on 2025-06-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_transaction_transaction_id_parsingrun"),
    ]

    operations = [
        # Removed duplicate AddField for transaction_id
    ]
