# Generated by Django 5.2 on 2025-05-26 21:34

from django.db import migrations, models
import django.db.models.deletion
import json


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_delete_processingtasktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="location",
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="business_rules",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="ai_generated_profile",
            field=models.JSONField(default=dict),
        ),
    ]
