# Generated by Django 5.2.4 on 2025-07-04 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_organizerformfield_organizerformtemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BinderRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_generated", models.BooleanField(default=False)),
                ("calculation_query", models.CharField(blank=True, max_length=255)),
                ("value", models.TextField(blank=True)),
                (
                    "reference_file",
                    models.FileField(blank=True, null=True, upload_to="binder_refs/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "tax_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binder_rows",
                        to="profiles.taxyear",
                    ),
                ),
            ],
        ),
    ]
