# Generated by Django 5.2 on 2025-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_add_missing_businessprofile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='additional_info',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='category_patterns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='common_expenses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='custom_categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='industry_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
