# Generated by Django 5.2.4 on 2025-07-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_binderrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="BinderRowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_generated", models.BooleanField(default=False)),
                ("calculation_query", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="organizerformresponse",
            name="field",
        ),
        migrations.RemoveField(
            model_name="organizerforminstance",
            name="tax_year",
        ),
        migrations.RemoveField(
            model_name="organizerforminstance",
            name="template",
        ),
        migrations.RemoveField(
            model_name="organizerformresponse",
            name="instance",
        ),
        migrations.AddField(
            model_name="binderrow",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="binder_rows",
                to="profiles.binderrowtemplate",
            ),
        ),
        migrations.DeleteModel(
            name="OrganizerFormField",
        ),
        migrations.DeleteModel(
            name="OrganizerFormTemplate",
        ),
        migrations.DeleteModel(
            name="OrganizerFormInstance",
        ),
        migrations.DeleteModel(
            name="OrganizerFormResponse",
        ),
    ]
