# Generated by Django 5.2 on 2025-05-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_businessprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='profiles.llmconfig'),
        ),
    ]
