# Generated by Django 5.2.4 on 2025-07-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0008_binderrowtemplate_remove_organizerformresponse_field_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="binderrow",
            name="calculation_query",
        ),
        migrations.RemoveField(
            model_name="binderrow",
            name="description",
        ),
        migrations.RemoveField(
            model_name="binderrow",
            name="label",
        ),
        migrations.RemoveField(
            model_name="binderrow",
            name="section",
        ),
        migrations.AlterField(
            model_name="binderrow",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="binder_rows",
                to="profiles.binderrowtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="binderrow",
            name="value",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
