# Generated by Django 5.2.4 on 2025-07-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_remove_binderrow_calculation_query_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("payee_lookup", "Payee Lookup"),
                    ("classification", "Classification"),
                    ("organizer_extraction", "Organizer Extraction"),
                ],
                max_length=20,
            ),
        ),
    ]
