# Generated by Django 5.2 on 2025-05-27 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_agent_llm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clients/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('other', 'Other')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('identified', 'Identified'), ('parsed', 'Parsed'), ('normalized', 'Normalized'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('status_detail', models.TextField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('parsed_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_files', to='profiles.businessprofile')),
                ('transactions', models.ManyToManyField(blank=True, related_name='source_files', to='profiles.transaction')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statement File',
                'verbose_name_plural': 'Statement Files',
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
