# Generated by Django 5.2.4 on 2025-07-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_processingtask_task_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklistattachment",
            name="checklist_item",
        ),
        migrations.AlterUniqueTogether(
            name="taxchecklistitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taxchecklistitem",
            name="business_profile",
        ),
        migrations.CreateModel(
            name="BinderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("attachment", "Attachment"),
                            ("form", "Form"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="form",
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("form_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("incomplete", "Incomplete"),
                            ("complete", "Complete"),
                            ("missing", "Missing"),
                        ],
                        default="not_started",
                        max_length=32,
                    ),
                ),
                (
                    "reference_file",
                    models.FileField(blank=True, null=True, upload_to="binder_refs/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_generated", models.BooleanField(default=False)),
                (
                    "previous_year_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binder_items",
                        to="profiles.taxyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinderItemField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("filled", "Filled"),
                            ("missing", "Missing"),
                            ("n/a", "N/A"),
                        ],
                        default="missing",
                        max_length=32,
                    ),
                ),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "binder_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="profiles.binderitem",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BinderRow",
        ),
        migrations.DeleteModel(
            name="BinderRowTemplate",
        ),
        migrations.DeleteModel(
            name="ChecklistAttachment",
        ),
        migrations.DeleteModel(
            name="TaxChecklistItem",
        ),
    ]
