# Generated by Django 5.2.1 on 2025-06-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_statementfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementfile",
            name="parser_module",
            field=models.CharField(
                blank=True,
                help_text="Registered parser module name (from ParserRegistry)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="statement_type",
            field=models.CharField(
                blank=True,
                help_text="Flexible statement type (e.g., VISA, checking, etc.)",
                max_length=100,
                null=True,
            ),
        ),
    ]
