# Generated by Django 5.2.4 on 2025-07-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_remove_checklistattachment_checklist_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxyear",
            options={
                "ordering": ["-year"],
                "verbose_name": "Binder",
                "verbose_name_plural": "Binders",
            },
        ),
    ]
