# Generated by Django 5.2.4 on 2025-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_alter_taxyear_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="binderitem",
            name="has_user_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="binderitem",
            name="page_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="binderitem",
            name="pdf_page_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="binderitem",
            name="thumbnail_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
