# Generated by Django 5.2.3 on 2025-06-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_add_review_flag_guidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_imported', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imported Parser',
                'verbose_name_plural': 'Imported Parsers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=10)),
                ('template', models.TextField(help_text='Regex or template logic for extraction')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
