# Generated by Django 5.2.3 on 2025-06-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_importedparser_parsertemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementfile',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='statement_file',
        ),
    ]
