# Generated by Django 5.2.3 on 2025-06-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_remove_statementfile_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='statement_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.statementfile'),
        ),
    ]
