# Generated by Django 5.2.3 on 2025-06-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_transaction_statement_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingtask',
            name='transactions',
        ),
    ]
