# Generated by Django 5.2.3 on 2025-06-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_remove_processingtask_transactions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImportedParser",
        ),
        migrations.DeleteModel(
            name="ParserTemplate",
        ),
    ]
