# Generated by Django 5.2.4 on 2025-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_binderitem_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="binderitem",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Summary from manifest for this item.", null=True
            ),
        ),
    ]
