# Generated by Django 5.2.4 on 2025-07-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_binderitem_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="client_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique, URL-safe identifier for this client. Used for lookups and URLs, but not the primary key. Auto-set after save.",
                max_length=64,
                null=True,
            ),
        ),
    ]
