# Generated by Django 5.2.3 on 2025-06-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_delete_importedparser_delete_parsertemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="classification_method",
            field=models.CharField(
                default=None,
                help_text="Method used to classify the transaction",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payee_extraction_method",
            field=models.CharField(
                default=None,
                help_text="Method used to extract the payee information",
                max_length=128,
            ),
        ),
    ]
