# Generated by Django 5.2.4 on 2025-09-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_alter_businessprofile_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="client_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique, URL-safe identifier for this client. Used for lookups and URLs, but not the primary key. Auto-set after save.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="client",
            field=models.ForeignKey(
                db_column="client_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.businessprofile",
                to_field="client_id",
            ),
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("payee_lookup", "Payee Lookup"),
                    ("classification", "Classification"),
                    ("organizer_extraction", "Organizer Extraction"),
                    ("batch_payee_lookup", "Batch Payee Lookup (OpenAI Batch API)"),
                    ("batch_classification", "Batch Classification (OpenAI Batch API)"),
                    (
                        "batch_full_workflow",
                        "Batch Full Workflow (Payee + Classification)",
                    ),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="statementfile",
            name="client",
            field=models.ForeignKey(
                db_column="client_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statement_files",
                to="profiles.businessprofile",
                to_field="client_id",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                db_column="client_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="profiles.businessprofile",
                to_field="client_id",
            ),
        ),
    ]
