# Generated by Django 5.2.1 on 2025-06-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsers_utilities", "0002_remove_samplestatement_uploaded_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedParser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("last_imported", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Imported Parser",
                "verbose_name_plural": "Imported Parsers",
                "ordering": ["name"],
            },
        ),
    ]
