# Generated by Django 5.2.4 on 2025-07-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0009_remove_binderrow_calculation_query_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerWorkbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_file", models.FileField(upload_to="organizers/originals/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_workbooks",
                        to="profiles.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("thumbnail", "Thumbnail"),
                            ("page_pdf", "Page PDF"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="organizers/outputs/")),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="organizers.organizerworkbook",
                    ),
                ),
            ],
        ),
    ]
