# Generated by Django 5.2.4 on 2025-07-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizerOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("thumbnail", "Thumbnail"),
                            ("page_pdf", "Page PDF"),
                            ("manifest", "Manifest"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="organizers/outputs/")),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerWorkbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_file", models.FileField(upload_to="organizers/originals/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("manifest_ready", "Manifest Ready"),
                            ("checklist_created", "Checklist Created"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "manifest_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("manifest_page_count", models.IntegerField(blank=True, null=True)),
                ("manifest_file_summary", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
