# Generated by Django 5.2.4 on 2025-07-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizers", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerworkbook",
            name="business_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizer_workbooks",
                to="profiles.businessprofile",
            ),
        ),
        migrations.AddField(
            model_name="organizerworkbook",
            name="tax_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizer_workbooks",
                to="profiles.taxyear",
            ),
        ),
        migrations.AddField(
            model_name="organizeroutput",
            name="workbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outputs",
                to="organizers.organizerworkbook",
            ),
        ),
    ]
