# Generated by Django 5.2.4 on 2025-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizerworkbook",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
