# Generated by Django 5.2.3 on 2025-07-01 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("personal", "Personal"),
                            ("transfer", "Transfer"),
                            ("ignore", "Ignore"),
                        ],
                        help_text="Primary classification of the transaction",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("manual", "Manual Override"),
                        ],
                        help_text="Confidence level in the classification",
                        max_length=20,
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        help_text="Explanation for the classification decision"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="Agent or user who created this classification",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.CharField(
                        help_text="Agent or user who last updated this classification",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active classification",
                    ),
                ),
                (
                    "version_notes",
                    models.TextField(
                        blank=True, help_text="Notes about why this version was created"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific expense category within the worksheet",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="profiles.irsexpensecategory",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the previous version of this classification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_version",
                        to="simple_classifications.simpleclassification",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simple_classification",
                        to="profiles.transaction",
                    ),
                ),
                (
                    "worksheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated IRS worksheet (e.g., 6A, Auto, HomeOffice)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="profiles.irsworksheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction", "created_at"],
                        name="simple_clas_transac_605186_idx",
                    ),
                    models.Index(
                        fields=["classification_type"],
                        name="simple_clas_classif_bd51ad_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="simple_clas_created_eeef72_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="simple_clas_updated_036a3c_idx"
                    ),
                ],
            },
        ),
    ]
