# Generated by Django 5.2.1 on 2025-06-07 19:35

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_transaction_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementfile",
            name="needs_account_number",
            field=models.BooleanField(
                default=False,
                help_text="True if this file needs an account number to be entered manually.",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="needs_account_number",
            field=models.BooleanField(
                default=False,
                help_text="True if this transaction needs an account number to be entered manually.",
            ),
        ),
        migrations.AlterField(
            model_name="statementfile",
            name="file",
            field=models.FileField(upload_to=profiles.models.statement_upload_to_uuid),
        ),
    ]
