# Generated by Django 5.2.1 on 2025-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_statementfile_needs_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementfile",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="account_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="statement_date",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="statement_period_end",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="statementfile",
            name="statement_period_start",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
