# Generated by Django 5.2.1 on 2025-06-04 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="statementfile",
            name="statement_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256 of file contents for deduplication",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="statementfile",
            constraint=models.UniqueConstraint(
                fields=("client", "statement_hash"), name="unique_client_statement_hash"
            ),
        ),
    ]
