# Generated by Django 5.2.1 on 2025-06-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_create_transactionclassification_table"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transactionclassification",
            new_name="profiles_tr_transac_002390_idx",
            old_name="transactionclassification_transaction_createdat_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionclassification",
            new_name="profiles_tr_transac_a4259e_idx",
            old_name="transactionclassification_transaction_isactive_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionclassification",
            new_name="profiles_tr_classif_da697e_idx",
            old_name="transactionclassification_type_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionclassification",
            new_name="profiles_tr_workshe_cd2bdb_idx",
            old_name="transactionclassification_worksheet_idx",
        ),
    ]
