# Generated by Django 5.2 on 2025-05-28 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=10)),
                ('template', models.TextField(help_text='Regex or template logic for extraction')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sample_statements/')),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=10)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers_utilities.parsertemplate')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers_utilities.samplestatement')),
            ],
        ),
    ]
