# Generated by Django 5.2.1 on 2025-06-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parsers_utilities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samplestatement",
            name="uploaded_by",
        ),
        migrations.DeleteModel(
            name="ExtractionResult",
        ),
        migrations.DeleteModel(
            name="SampleStatement",
        ),
    ]
