# Generated by Django 5.2.1 on 2025-06-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_transaction_transaction_id"),
    ]

    operations = []
