version: '3.9'

services:
  django:
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:9000"
    restart: on-failure

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

volumes:
  postgres_data: 